# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_donor_identityhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
