# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_donor_anonymized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='identityhash',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name=b'Email Hash'),
        ),
    ]
